import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
  {
    // components/ui/ is generated by the shadcn CLI — we regenerate rather than hand-edit,
    // so an inline eslint-disable would be wiped on the next `shadcn add`. carousel.tsx
    // syncs embla's state into React from an effect, which trips this rule by design.
    // hooks/use-mobile.ts is generated by the same CLI (it ships with `add sidebar`) and reads
    // the viewport width into state from an effect for the same reason. Listed by name rather
    // than as hooks/** so hand-written hooks added later are still linted.
    files: ["components/ui/**", "hooks/use-mobile.ts"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
