-- Initial schema for Chique's Swiet Mofo.
--
-- Replaces the three tables that were built by hand in the Table Editor. Those
-- were scratch work with no data worth keeping, so this drops and recreates them
-- rather than trying to alter them into shape.

-- ---------------------------------------------------------------------------
-- Clean slate
-- ---------------------------------------------------------------------------
-- "cascade" also removes anything that depends on these tables (policies,
-- indexes, constraints). "if exists" keeps this from failing on a fresh database.

drop table if exists public.recipe_ingredients cascade;
drop table if exists public.recipe_images cascade;
drop table if exists public.recipe_steps cascade;
drop table if exists public.recipes cascade;
drop type if exists public.recipe_difficulty;

-- ---------------------------------------------------------------------------
-- Enum: difficulty
-- ---------------------------------------------------------------------------
-- A column typed as this enum can only ever hold one of these three values.
-- `npm run db:types` turns it into a TypeScript union, so a typo is a compile
-- error rather than a bad row. Adding a value later is easy; removing or
-- reordering is not, so keep the list short.

create type public.recipe_difficulty as enum ('easy', 'medium', 'hard');

-- ---------------------------------------------------------------------------
-- Trigger function: keep updated_at honest
-- ---------------------------------------------------------------------------
-- Postgres maintains updated_at, not the app. If the app owned it, any edit made
-- from Studio or from a future script would silently leave a stale timestamp.
--
-- `set search_path = ''` is a Supabase security convention: it forces every name
-- inside the function to be fully qualified, so nobody can shadow a table or
-- function name to hijack what this runs.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- recipes
-- ---------------------------------------------------------------------------

create table public.recipes (
  id           bigint generated by default as identity primary key,

  -- The URL segment, e.g. /recipes/gestoofde-bakbanaan. Not null because it is
  -- how a recipe is addressed, unique because two recipes sharing a slug would
  -- make a lookup return two rows.
  slug         text not null unique
                 check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),

  -- trim() guards against a title of only spaces, which is not null but is still
  -- effectively empty.
  title        text not null check (length(trim(title)) > 0),
  description  text,

  difficulty   public.recipe_difficulty,
  time_minutes int check (time_minutes > 0),

  -- Added on top of what you had. Standard for a recipe site; drop the column if
  -- you don't want it.
  servings     int check (servings > 0),

  -- not null + default false: a recipe is a draft until you say otherwise. The
  -- old nullable version had three states (true / false / null), and `where
  -- published = true` silently skips nulls.
  published    boolean not null default false,

  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create trigger recipes_set_updated_at
  before update on public.recipes
  for each row execute function public.set_updated_at();

-- Serves the public recipe list: filter to published, newest first.
create index recipes_published_created_at_idx
  on public.recipes (published, created_at desc);

-- ---------------------------------------------------------------------------
-- recipe_steps
-- ---------------------------------------------------------------------------

create table public.recipe_steps (
  id          bigint generated by default as identity primary key,

  -- `references` is the foreign key that was missing. It makes a step pointing
  -- at a non-existent recipe impossible, and `on delete cascade` means deleting
  -- a recipe deletes its steps automatically — no cleanup code in the app.
  recipe_id   bigint not null references public.recipes (id) on delete cascade,

  step_number int not null check (step_number > 0),
  instruction text not null check (length(trim(instruction)) > 0),

  -- Path inside a Supabase Storage bucket, not a URL. Optional per-step photo.
  image_path  text,

  -- Two step 3s in one recipe is a bug, so the database refuses it. This also
  -- indexes recipe_id, which a foreign key needs to make cascades and joins fast.
  unique (recipe_id, step_number)
);

-- ---------------------------------------------------------------------------
-- recipe_ingredients
-- ---------------------------------------------------------------------------

create table public.recipe_ingredients (
  id        bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes (id) on delete cascade,

  -- Display order. Ingredient lists are ordered, and row order in Postgres is
  -- never guaranteed, so ordering has to be stored explicitly. No default, so
  -- the write path is forced to be deliberate about it.
  sort_order int not null check (sort_order >= 0),

  name       text not null check (length(trim(name)) > 0),

  -- numeric, not float: exact decimals. Nullable on purpose — "salt, to taste"
  -- has no amount and no unit.
  amount     numeric check (amount > 0),
  unit       text,

  unique (recipe_id, sort_order)
);

-- ---------------------------------------------------------------------------
-- recipe_images
-- ---------------------------------------------------------------------------

create table public.recipe_images (
  id           bigint generated by default as identity primary key,
  recipe_id    bigint not null references public.recipes (id) on delete cascade,

  storage_path text not null check (length(trim(storage_path)) > 0),

  -- Alt text for screen readers. Nullable, because a purely decorative image
  -- should have empty alt rather than invented alt.
  alt          text,

  -- Defaults added: the old version required both on every insert.
  sort_order   int not null default 0,
  is_primary   boolean not null default false,

  unique (recipe_id, storage_path)
);

-- A partial unique index: unique on recipe_id, but only across rows where
-- is_primary is true. Result — unlimited images per recipe, at most one primary.
create unique index recipe_images_one_primary_idx
  on public.recipe_images (recipe_id)
  where is_primary;

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------
-- This is the only thing protecting writes. The publishable key ships to every
-- visitor's browser, so anyone can call the API as `anon` — RLS decides what
-- that gets them.
--
-- Enabling RLS with no policies denies everything. Policies then add back
-- specific permissions.
--
-- IMPORTANT: `authenticated` means *any* logged-in user, not specifically you.
-- That is only equivalent to "the owner" while signups are disabled.

alter table public.recipes            enable row level security;
alter table public.recipe_steps       enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.recipe_images      enable row level security;

-- Table-level grants are a separate layer from RLS, and both must allow an
-- operation for it to succeed. Granted explicitly rather than relying on the
-- project's default privileges.
grant select                 on public.recipes            to anon, authenticated;
grant select                 on public.recipe_steps       to anon, authenticated;
grant select                 on public.recipe_ingredients to anon, authenticated;
grant select                 on public.recipe_images      to anon, authenticated;

grant insert, update, delete on public.recipes            to authenticated;
grant insert, update, delete on public.recipe_steps       to authenticated;
grant insert, update, delete on public.recipe_ingredients to authenticated;
grant insert, update, delete on public.recipe_images      to authenticated;

-- recipes -------------------------------------------------------------------

-- Visitors see published recipes only. Drafts are invisible to anonymous users.
create policy "anon reads published recipes"
  on public.recipes for select
  to anon
  using (published);

-- The owner sees everything, drafts included, so /admin can list them.
create policy "authenticated reads all recipes"
  on public.recipes for select
  to authenticated
  using (true);

-- `for all` covers insert, update and delete. `using` gates which existing rows
-- may be touched; `with check` gates what new or updated rows may look like.
create policy "authenticated writes recipes"
  on public.recipes for all
  to authenticated
  using (true)
  with check (true);

-- recipe_steps --------------------------------------------------------------

-- A step is readable only when its parent recipe is. Without this, a draft's
-- instructions would be readable even though the recipe itself is hidden.
create policy "anon reads steps of published recipes"
  on public.recipe_steps for select
  to anon
  using (
    exists (
      select 1 from public.recipes r
      where r.id = recipe_steps.recipe_id and r.published
    )
  );

create policy "authenticated reads all steps"
  on public.recipe_steps for select
  to authenticated
  using (true);

create policy "authenticated writes steps"
  on public.recipe_steps for all
  to authenticated
  using (true)
  with check (true);

-- recipe_ingredients --------------------------------------------------------

create policy "anon reads ingredients of published recipes"
  on public.recipe_ingredients for select
  to anon
  using (
    exists (
      select 1 from public.recipes r
      where r.id = recipe_ingredients.recipe_id and r.published
    )
  );

create policy "authenticated reads all ingredients"
  on public.recipe_ingredients for select
  to authenticated
  using (true);

create policy "authenticated writes ingredients"
  on public.recipe_ingredients for all
  to authenticated
  using (true)
  with check (true);

-- recipe_images -------------------------------------------------------------

create policy "anon reads images of published recipes"
  on public.recipe_images for select
  to anon
  using (
    exists (
      select 1 from public.recipes r
      where r.id = recipe_images.recipe_id and r.published
    )
  );

create policy "authenticated reads all images"
  on public.recipe_images for select
  to authenticated
  using (true);

create policy "authenticated writes images"
  on public.recipe_images for all
  to authenticated
  using (true)
  with check (true);
